plugins {
    id 'java-library'
    id 'maven-publish'
    id 'idea'
    id 'net.neoforged.moddev.legacyforge' version '2.0.141'
    id 'io.freefair.lombok' version '9.2.0'
}

version = mod_version
group = mod_group_id

repositories {
    mavenLocal()
    flatDir {
        dir "libs"
    }
    mavenCentral()

    maven { url = 'https://maven.gtodyssey.com/releases' }
    exclusiveContent { // Curseforge Maven
        forRepository { maven { url = "https://cursemaven.com" } }
        filter { includeGroup("curse.maven") }
    }

    exclusiveContent { // terraformers - EMI
        forRepository { maven { url = "https://maven.terraformersmc.com/releases/" } }
        filter { includeGroup("dev.emi") }
    }

    exclusiveContent { // Xaero's
        forRepository { maven { url = "https://chocolateminecraft.com/maven/" } }
        filter { includeGroupAndSubgroups("xaero") }
    }

    maven {
        url "https://maven.shadowsoffire.dev/releases"
        content {
            includeGroup "dev.shadowsoffire"
        }
    }
    maven {
        name = 'GeckoLib'
        url 'https://dl.cloudsmith.io/public/geckolib3/geckolib/maven/'
        content {
            includeGroupByRegex("software\\.bernie.*")
            includeGroup("com.eliotlash.mclib")
        }
    }

    maven { // JEI
        name = "Jared's Maven"
        url = "https://maven.blamejared.com/"
    }

    maven { // JEI mirror, AE2
        name = "ModMaven"
        url = "https://modmaven.dev"
    }

    maven {
        url "https://maven.firstdarkdev.xyz/snapshots/"
    }
    maven {
        url "https://maven.quiltmc.org/repository/release/"
    }
    maven {
        url "https://maven.parchmentmc.org"
    }
    maven {
        url "https://maven.architectury.dev/"
    }
    maven {
        url "https://maven.teamresourceful.com/repository/maven-public/"
    }
    maven {
        url "https://maven.jt-dev.tech/releases/"
    }
    maven {
        url "https://mvnrepository.com/artifact/com.hollingsworth.ars_nouveau"
    }
    maven {
        url "https://maven.bawnorton.com/releases"
    }
    maven {
        url "https://maven.enjarai.dev/mirrors"
    }
    maven {
        url "https://maven.blamejared.com/vazkii/botania/Botania/"
    }
    maven {
        url "https://maven.twelveiterations.com/repository/maven-public/"

        content {
            includeGroup "net.blay09.mods"
        }
    }
}

base {
    archivesName = mod_id
}

java.toolchain.languageVersion = JavaLanguageVersion.of(17)

tasks.withType(JavaCompile).configureEach {
    options.encoding = "UTF-8"
}

mixin {
    add sourceSets.main, "${project.mod_id}.refmap.json"
    config "${project.mod_id}.mixins.json"
}

legacyForge {
    version = "${project.minecraft_version}-${project.forge_version}"

    parchment {
        minecraftVersion = project.parchment_minecraft_version
        mappingsVersion = project.parchment_mappings_version
    }

    runs {
        client {
            client()
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }

        server {
            server()
            programArgument '--nogui'
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }

        gameTestServer {
            type = "gameTestServer"
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }

        data {
            data()
            programArguments.addAll '--mod', project.mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
        }

        configureEach {
            systemProperty 'forge.logging.markers', 'REGISTRIES'
            logLevel = org.slf4j.event.Level.DEBUG
        }
    }

    mods {
        "${mod_id}" {
            sourceSet(sourceSets.main)
        }
    }

    accessTransformers = project.files('src/main/resources/META-INF/accesstransformer.cfg')
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

afterEvaluate {
    tasks.withType(org.gradle.jvm.tasks.Jar).configureEach {
        manifest.attributes([
                'MixinConfigs': "${mod_id}.mixins.json",
                'Specification-Title': project.name,
                'Specification-Version': mod_version,
                'Implementation-Title': base.archivesName,
                'Implementation-Version': version,
                'Sealed': 'true'
        ])
    }
}

var generateModMetadata = tasks.register("generateModMetadata", ProcessResources) {
    var replaceProperties = [
            forge_version            : forge_version,
            forge_version_range      : forge_version_range,
            loader_version_range   : loader_version_range,
            mod_id                 : mod_id,
            mod_name               : mod_name,
            mod_license            : mod_license,
            mod_version            : mod_version,
            mod_authors            : mod_authors,
            mod_description        : mod_description
    ]
    inputs.properties replaceProperties
    expand replaceProperties
    from "src/main/templates"
    into "build/generated/sources/modMetadata"
}

sourceSets.main.resources.srcDir generateModMetadata
legacyForge.ideSyncTask generateModMetadata

idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}

dependencies {
    implementation("org.lwjgl:lwjgl:3.3.2")
    implementation("org.lwjgl:lwjgl-opengl:3.3.2")

    compileOnly("org.projectlombok:lombok:1.18.42")
    annotationProcessor("org.projectlombok:lombok:1.18.42")

    annotationProcessor("org.spongepowered:mixin:0.8.7:processor")
    api(annotationProcessor("io.github.llamalad7:mixinextras-common:0.5.5"))

    modImplementation("curse.maven:modernfix-790626:7928686")
    modImplementation("curse.maven:ferritecore-429235:4810975")
    modImplementation("curse.maven:spark-361579:4738952")

    modImplementation("appeng:appliedenergistics2-forge:15.4.10")
    modRuntimeOnly("org.appliedenergistics:guideme:20.1.15")

    jarJar(implementation("com.gto.fastcollection:FastCollection:26.8.7"))

    modImplementation("curse.maven:farmers-delight-398521:8083474")
}